version: '3.8'

services:
  frontend-loyalty:
    container_name: loyalty-frontend
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    # depends_on:
    #   - backend
    networks:
      - nginx-network

networks:
  nginx-network:
    external: true
